### ISSUE TITLE
營業時間 of Restaurant

### ISSUE THREAD

**Issue by yenting-biao** [yenting-biao/FoodDate#15]
I think we may need another column, 營業時間, for each restaurant.

**Comment by nukkk97** [comment]
there is relevant information in my json files.
e.g.
"openingHours": [
    {
      "day": "星期五",
      "hours": "17:00 to 22:00"
    },
    {
      "day": "星期六",
      "hours": "12:00 to 14:00, 17:00 to 22:00"
    },
    {
      "day": "星期日",
      "hours": "12:00 to 14:00, 17:00 to 22:00"
    },
    {
      "day": "星期一",
      "hours": "休息"
    },
    {
      "day": "星期二",
      "hours": "17:00 to 22:00"
    },
    {
      "day": "星期三",
      "hours": "17:00 to 22:00"
    },
    {
      "day": "星期四",
      "hours": "17:00 to 22:00"
    }
  ]

**Comment by yenting-biao** [comment]
Add it in db.

**Comment by yenting-biao** [comment]
Add it in db later.

**Comment by togimoto** [comment]
> there is relevant information in my json files. e.g. "openingHours": [ { "day": "星期五", "hours": "17:00 to 22:00" }, { "day": "星期六", "hours": "12:00 to 14:00, 17:00 to 22:00" }, { "day": "星期日", "hours": "12:00 to 14:00, 17:00 to 22:00" }, { "day": "星期一", "hours": "休息" }, { "day": "星期二", "hours": "17:00 to 22:00" }, { "day": "星期三", "hours": "17:00 to 22:00" }, { "day": "星期四", "hours": "17:00 to 22:00" } ]

I will follow this format.
