### ISSUE TITLE
Need modification in Header.tsx

### ISSUE THREAD

**Issue by yenting-biao** [yenting-biao/FoodDate#34]
Note that in Header.tsx,148: 
AuthForm onCloseAuthModal={handleCloseAuthModal}
Still need to be modified since I discard the modal props.

_Originally posted by @nukkk97 in https://github.com/yenting-biao/FoodDate/issues/33#issuecomment-1869612659_
            

-> I will fix it after the PR is merged.

**Comment by nukkk97** [comment]
pr #36 fixed it.
