### ISSUE TITLE
Bug(auth): logged-in user can access log in page

### ISSUE THREAD

**Issue by togimoto** [yenting-biao/FoodDate#44]
If a logged-in user visited /login, the user should be redirected to /profile.

**Comment by nukkk97** [comment]
Already fixed. Not yet pushed.

**Comment by yenting-biao** [comment]
After log in, the user should be redirect to /profile

**Comment by nukkk97** [comment]
#47 fixed

**Comment by yenting-biao** [comment]
You can link an issue to a PR next time. When the PR is approved and merged, the issue will be closed automatically.
